### ISSUE TITLE
Access Deny

### ISSUE THREAD

**Issue by BruceGeng2012** [Raymai97/SuperCMD#1]
Hi Raymai97

C:\Program Files\WindowsApps\SpotifyAB.SpotifyMusic_1.166.580.0_x86__zpdnekdrzrea0>copy d:\1.txt
Deny Access。
Copyed        0 个文件。

Try copy and past sth here, but fail. Help plz....lol thx....

**Comment by Raymai97** [comment]
Sorry, but you hit the jackpot, pal.

Microsoft has poured their maximum effort to protect the WindowsApps folder. Almost all files are strictly unmodifiable even if you modify the NTFS permission/owner settings or run with token of TrustedInstaller. I have yet to find a way to circumvent it in "current OS" user-mode.

NSudo 8.2 has similar result:
![image](https://user-images.githubusercontent.com/3296077/132250206-ada41cfa-219d-4a61-af5e-a11419d3ac29.png)

You can try to do what you want to do in WinPE or dual-boot OS. But be reminded, WindowsApps is highly sensitive to tampering, so it's likely you would break your "Spotify" app if you try to "mod" anything.

**Comment by BruceGeng2012** [comment]
Mr Chee Boon,

Gotcha what u say...Appreciate it dude...Dont wanna try anymore coz already
lose control of winstore...Finally subscribed & bought the premium...

Thanks for your reply and support. cool day bro...

Bruce
